feat: Выполнить ТЗ№14
elayhan/java-shareit pull request #2
Opened 2023-06-24 09:16 UTC by elayhan

2023-06-25 15:13 UTC, AnastasiyaFomkina requested changes

2023-06-25 15:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDateTime start;
Лучше добавить [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates) для полей с датой, так мы можем избежать множественных ошибок при парсинге даты из json

2023-06-25 15:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Data
_Саморазвитие_
Лучше не использовать `@Data`, так как она несет за собой много скрытых проблем. Вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-06-25 15:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)
Нужно избавиться от нее во всех сущностях проекта

2023-06-25 15:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-06-25 15:13 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
И здесь очень помогут паттерны

2023-06-25 15:13 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-06-28 19:26 UTC, elayhan commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
Почитал, решил что этому паттерну тут не место. "Богомерзкий" свич поменял на мап ;)

2023-06-28 19:27 UTC, elayhan commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
На users точно больше не надо =)

2023-06-29 09:32 UTC, AnastasiyaFomkina approved these changes

2023-06-29 10:03 UTC, merged